
/datum/map/system_conquest
	allowed_jobs = list(
	/datum/job/colonist,
	/datum/job/colonist/mayor,
	/datum/job/colonist/aerodrome,
	/datum/job/colonist/biodome_worker,
	/datum/job/colonist/casino_owner,
	/datum/job/colonist/hospital_worker,
	/datum/job/colonist/pharmacist,
	/datum/job/colonist/colonist_marshal,
	/datum/job/colonist/bartender,
	/datum/job/colonist/chef,
	/datum/job/colonist/librarian_museum,
	/datum/job/unsc/spartan_two,
	/datum/job/unsc/crew,
	/datum/job/unsc/medical,
	/datum/job/unsc/marine,
	/datum/job/unsc/marine/specialist,
	/datum/job/unsc/marine/squad_leader,
	/datum/job/unsc/odst,
	/datum/job/unsc/odst/squad_leader,
	/datum/job/unsc/commanding_officer,
	/datum/job/unsc/executive_officer,
	/datum/job/unsc/oni/field_agent,
	/datum/job/unsc/oni/research,
	/datum/job/unsc/oni/research/director,
	/datum/job/unsc_ai,
	/datum/job/covenant/AI,
	/datum/job/covenant/huragok,
	/datum/job/covenant/sangheili_minor,
	/datum/job/covenant/sangheili_major,
	/datum/job/covenant/sangheili_ultra,
	/datum/job/covenant/sangheili_shipmaster,
	/datum/job/covenant/sangheili_specops,
	/datum/job/covenant/lesser_prophet,
	/datum/job/covenant/kigyarminor,
	/datum/job/covenant/unggoy_minor,
	/datum/job/covenant/unggoy_major,
	/datum/job/covenant/unggoy_ultra,
	/datum/job/covenant/unggoy_deacon,
	/datum/job/covenant/unggoy_heavy,
	/datum/job/covenant/unggoy_specops,
	/datum/job/covenant/skirmmurmillo,
	/datum/job/covenant/skirmcommando,
	/datum/job/covenant/skirmchampion,
	/datum/job/covenant/brute_minor,
	/datum/job/covenant/brute_major,
	/datum/job/covenant/brute_captain,
	/datum/job/covenant/yanmee_minor,
	/datum/job/covenant/yanmee_major,
	/datum/job/covenant/yanmee_ultra,
	/datum/job/covenant/yanmee_leader,
	/datum/job/covenant/mgalekgolo,
	/datum/job/geminus_innie,
	/datum/job/geminus_innie/officer,
	/datum/job/geminus_innie/commander,
	/datum/job/insurrectionist_ai,
	/datum/job/geminus_x52/researcher,
	/datum/job/geminus_x52/research_director,
	/datum/job/soe_commando,
	/datum/job/soe_commando_officer,
	/datum/job/soe_commando_captain,
	/datum/job/geminus_innie/orion_defector,
		)

	allowed_spawns = list(
		DEFAULT_SPAWNPOINT_ID,
		"UNSC Base Spawns",
		"UNSC Base Fallback Spawns",
		"Covenant Base Fallback Spawns",
		"Innie Base Fallback Spawns"
		)

	default_spawn = DEFAULT_SPAWNPOINT_ID
