#define SETUP_NAME "name"
#define SETUP_OBJ_SHEET "icon"
#define SETUP_ONMOB_SHEET "item_icons"
#define SETUP_ICON_STATE "icon_state"
#define SETUP_ITEM_STATE "item_state"
#define SETUP_ITEM_STATE_SLOTS "item_state_slots"
#define SETUP_SPECIES_OBJ "sprite_sheets_obj"
#define SETUP_SPECIES_ONMOB "sprite_sheets"
