
#undef REWARD_FAVOUR
#undef REWARD_CREDITS
//
#undef OBJ_KILL
#undef OBJ_ASSASSINATE
#undef OBJ_STEAL
//
#undef STATUS_AVAIL
#undef STATUS_PROGRESS
#undef STATUS_FAIL
#undef STATUS_WON
#undef STATUS_ABANDON
#undef STATUS_TIMEOUT
