version: "3"
services:
  db:
    build: ./sql
    image: bs12-db:latest
    networks:
      - internal
    volumes:
      - "./sql/test_db:/var/lib/mysql"
  game:
    build: .
    image: bs12:latest
    networks:
      - internal
    ports:
      - "8000:8000"
networks:
  internal: