
#define CARGO_CRATE_COST_MULTI 10

#define REWARD_FAVOUR 100
#define REWARD_CREDITS 10000
//
#define OBJ_KILL 1
#define OBJ_ASSASSINATE 2
#define OBJ_STEAL 3
//
#define STATUS_AVAIL 0
#define STATUS_REJECT 0
#define STATUS_PROGRESS 1
#define STATUS_FAIL 2
#define STATUS_WON 3
#define STATUS_ABANDON 4
#define STATUS_TIMEOUT 5
