/proc/slot_to_description(slot)
	switch(slot)
		if(slot_back) return "Back"
		if(slot_r_hand) return "Right Hand"
		if(slot_l_hand) return "Left Hand"
		if(slot_w_uniform) return "Uniform"
		if(slot_head) return "Head"
		if(slot_wear_suit) return "Suit"
		if(slot_l_ear) return "Left Ear"
		if(slot_r_ear) return "Right Ear"
		if(slot_belt) return "Belt"
		if(slot_shoes) return "Shoes"
		if(slot_wear_mask) return "Mask"
		if(slot_handcuffed) return "Handcuffed"
		if(slot_legcuffed) return "Legcuffed"
		if(slot_wear_id) return "ID"
		if(slot_gloves) return "Gloves"
		if(slot_glasses) return "Glasses"
		if(slot_s_store) return "Suit Store"
		if(slot_tie) return "Accessory"
	throw EXCEPTION("Cannot provide description for unknown slot: [slot]!")
