// MySQL configuration
var/global/sqlenabled   = FALSE
var/global/sqladdress   = ""
var/global/sqlport      = ""
var/global/sqldb        = ""
var/global/sqllogin     = ""
var/global/sqlpass      = ""
var/global/sqlfdbkdb    = ""
var/global/sqlfdbklogin = ""
var/global/sqlfdbkpass  = ""
var/global/DBConnection/dbcon = new
var/global/DBConnection/dbcon_old = new
