/material/proc/get_recipes(var/reinf_mat)
	var/key = reinf_mat ? reinf_mat : "base"
	if(!LAZYACCESS(recipes,key))
		LAZYSET(recipes,key,generate_recipes(reinf_mat))
	return recipes[key]

/material/proc/create_recipe_list(base_type, var/reinforce_material)
	. = list()
	for(var/recipe_type in subtypesof(base_type))
		. += new recipe_type(src, reinforce_material)

/material/proc/generate_recipes(var/reinforce_material)
	. = list()

	if(opacity < 0.6)
		. += new/datum/stack_recipe/furniture/borderwindow(src, reinforce_material)
		. += new/datum/stack_recipe/furniture/fullwindow(src, reinforce_material)
		if(integrity > 75 || reinforce_material)
			. += new/datum/stack_recipe/furniture/windoor(src, reinforce_material)

	// If is_brittle() returns true, these are only good for a single strike.
	. += new/datum/stack_recipe/baseball_bat(src, reinforce_material)
	. += new/datum/stack_recipe/ashtray(src, reinforce_material)
	. += new/datum/stack_recipe/coin(src, reinforce_material)
	. += new/datum/stack_recipe/spoon(src, reinforce_material)
	. += new/datum/stack_recipe/ring(src, reinforce_material)
		
	if(integrity>50)
		. += new/datum/stack_recipe/furniture/chair(src, reinforce_material) //NOTE: the wood material has it's own special chair recipe
		. += new/datum/stack_recipe_list("padded [display_name] chairs", create_recipe_list(/datum/stack_recipe/furniture/chair/padded, reinforce_material))
	if(integrity>=50)
		. += new/datum/stack_recipe/furniture/door(src, reinforce_material)
		. += new/datum/stack_recipe/furniture/barricade(src, reinforce_material)
		. += new/datum/stack_recipe/furniture/stool(src, reinforce_material)
		. += new/datum/stack_recipe/furniture/bar_stool(src, reinforce_material)
		. += new/datum/stack_recipe/furniture/bed(src, reinforce_material)
		. += new/datum/stack_recipe/lock(src, reinforce_material)
		. += new/datum/stack_recipe/railing(src, reinforce_material)
		. += new/datum/stack_recipe/rod(src, reinforce_material)

	if(hardness>50)
		. += new/datum/stack_recipe/fork(src, reinforce_material)
		. += new/datum/stack_recipe/knife(src, reinforce_material)
		. += new/datum/stack_recipe/bell(src, reinforce_material)
		. += new/datum/stack_recipe/blade(src, reinforce_material)

/material/steel/generate_recipes(var/reinforce_material)
	. = ..()
	. += new/datum/stack_recipe_list("office chairs",list(
		new/datum/stack_recipe/furniture/chair/office/dark(src, reinforce_material),
		new/datum/stack_recipe/furniture/chair/office/light(src, reinforce_material)
		))
	. += new/datum/stack_recipe_list("comfy office chairs", create_recipe_list(/datum/stack_recipe/furniture/chair/office/comfy, reinforce_material))
	. += new/datum/stack_recipe_list("comfy chairs", create_recipe_list(/datum/stack_recipe/furniture/chair/comfy, reinforce_material))
	. += new/datum/stack_recipe_list("armchairs", create_recipe_list(/datum/stack_recipe/furniture/chair/arm, reinforce_material))
	. += new/datum/stack_recipe/key(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/table_frame(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/rack(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/closet(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/canister(src, reinforce_material)
	. += new/datum/stack_recipe/cannon(src, reinforce_material)
	. += create_recipe_list(/datum/stack_recipe/tile/metal, reinforce_material)
	. += new/datum/stack_recipe/furniture/computerframe(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/girder(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/wall(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/machine(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/turret(src, reinforce_material)
	. += new/datum/stack_recipe_list("airlock assemblies", create_recipe_list(/datum/stack_recipe/furniture/door_assembly, reinforce_material))
	. += new/datum/stack_recipe/grenade(src, reinforce_material)
	. += new/datum/stack_recipe/light(src, reinforce_material)
	. += new/datum/stack_recipe/light_small(src, reinforce_material)
	. += new/datum/stack_recipe/light_switch(src, reinforce_material)
	. += new/datum/stack_recipe/light_switch/windowtint(src, reinforce_material)
	. += new/datum/stack_recipe/apc(src, reinforce_material)
	. += new/datum/stack_recipe/air_alarm(src, reinforce_material)
	. += new/datum/stack_recipe/fire_alarm(src, reinforce_material)
	. += new/datum/stack_recipe_list("modular computer frames", create_recipe_list(/datum/stack_recipe/computer, reinforce_material))

/material/plasteel/generate_recipes(var/reinforce_material)
	. = ..()
	. += new/datum/stack_recipe/ai_core(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/crate(src, reinforce_material)
	. += new/datum/stack_recipe/grip(src, reinforce_material)

/material/stone/generate_recipes(var/reinforce_material)
	. = ..()
	. += new/datum/stack_recipe/furniture/planting_bed(src, reinforce_material)

/material/plastic/generate_recipes(var/reinforce_material)
	. = ..()
	. += new/datum/stack_recipe/furniture/crate/plastic(src, reinforce_material)
	. += new/datum/stack_recipe/bag(src, reinforce_material)
	. += new/datum/stack_recipe/ivbag(src, reinforce_material)
	. += create_recipe_list(/datum/stack_recipe/cartridge, reinforce_material)
	. += create_recipe_list(/datum/stack_recipe/tile/light, reinforce_material)
	. += new/datum/stack_recipe/hazard_cone(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/flaps(src, reinforce_material)

/material/wood/generate_recipes(var/reinforce_material)
	. = ..()
	. += new/datum/stack_recipe/sandals(src, reinforce_material)
	. += new/datum/stack_recipe/tile/wood(src, reinforce_material)
	. += create_recipe_list(/datum/stack_recipe/furniture/chair/wood, reinforce_material)
	. += new/datum/stack_recipe/crossbowframe(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/coffin(src, reinforce_material)
	. += new/datum/stack_recipe/beehive_assembly(src, reinforce_material)
	. += new/datum/stack_recipe/beehive_frame(src, reinforce_material)
	. += new/datum/stack_recipe/furniture/bookcase(src, reinforce_material)
	. += new/datum/stack_recipe/zipgunframe(src, reinforce_material)
	. += new/datum/stack_recipe/coilgun(src, reinforce_material)
	. += new/datum/stack_recipe/stick(src, reinforce_material)
	. += new/datum/stack_recipe/noticeboard(src, reinforce_material)

/material/cardboard/generate_recipes(var/reinforce_material)
	. = ..()
	. += create_recipe_list(/datum/stack_recipe/box, reinforce_material)
	. += new/datum/stack_recipe/cardborg_suit(src, reinforce_material)
	. += new/datum/stack_recipe/cardborg_helmet(src, reinforce_material)
	. += new/datum/stack_recipe_list("folders", create_recipe_list(/datum/stack_recipe/folder, reinforce_material))