{
 "title": "Game",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Controllers %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ss13_controller_time_seconds[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tick Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(byond_world_time_seconds[1m])"
    }
   ]
  },
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "byond_players" }
   ]
  },
  {
   "title": "Runlevel",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ss13_master_runlevel" }
   ]
  },
  {
   "title": "Scrape duration during round",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"bs12\"} and (ss13_master_runlevel >= 3)"
    }
   ]
  }
 ]
}