{
 "title": "Garbage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "SS Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ss13_controller_time_seconds{name=\"Garbage\"}[1m])",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Hard Deletions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(ss13_garbage_total_cleaned{type=\"del\"}[1m])",
     "legendFormat": "deletions"
    }
   ]
  },
  {
   "title": "GC Queue Length (log scale)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ss13_garbage_queue_length", "legendFormat": "Queue {{ queue }}" }
   ]
  },
  {
   "title": "Queue Passes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ss13_garbage_queue_results{result=\"pass\"}[1m])",
     "legendFormat": "Queue {{queue}}"
    }
   ]
  },
  {
   "title": "Queue Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ss13_garbage_queue_results{result=\"fail\"}[1m])",
     "legendFormat": "Queue {{queue}}"
    }
   ]
  }
 ]
}