
#undef COMMS_CUTIN_EVENT_CHANCE
#undef DETACHMENT_ROLES
#undef ONI_ROLES
#undef MISC_UNSC_ROLES
#undef COVENANT_ROLES
#undef COMMS_CUTIN_EVENT_MIN
#undef COMMS_CUTIN_EVENT_MAX
#undef COMMS_CUTIN_EVENT_DURATION
#undef FLOOD_EVENT_Z_START
#undef FLOOD_EVENT_Z_END
#undef FLOOD_EVENT_MINOR_START
#undef FLOOD_EVENT_MAJOR_START
#undef FLOOD_EVENT_REPEAT_TIME
#undef MODE_CONFIG_DEADLINE_TIME
#undef EVAC_TIME
