#define ALLERGEN_ALCOHOL "Alcohol"
#define ALLERGEN_CITRUS "Citrus"
#define ALLERGEN_EGG "Egg"
#define ALLERGEN_FRUIT "Fruit"
#define ALLERGEN_LACTOSE "Lactose"
#define ALLEGERN_MEAT "Meat"
#define ALLERGEN_MEAT_POULTRY "Meat, Poultry"
#define ALLERGEN_MEAT_RED "Meat, Red"
#define ALLERGEN_NUTS "Nuts"
#define ALLERGEN_PLANTS "Plants"
#define ALLERGEN_RICE "Rice"
#define ALLERGEN_SESAME "Sesame"
#define ALLERGEN_SHELLFISH "Shellfish"
#define ALLERGEN_SOY "Soy"
#define ALLERGEN_WHEAT "Wheat"
