// General aspects.
#define ASPECT_HOTSTUFF         "Hot Stuff"
#define ASPECT_HARDY            "Hardy"
#define ASPECT_THICKBONES       "Thick Bones"
#define ASPECT_SCARRED          "Scarred"
#define ASPECT_APPRAISER        "Appraiser"
#define ASPECT_SHARPEYED        "Sharp-Eyed"
#define ASPECT_RADHARDENED      "Lead Poisoning"
#define ASPECT_UNCANNY          "Uncanny"
#define ASPECT_FRAGILE          "Fragile"
#define ASPECT_GLASS_BONES      "Glass Bones"
#define ASPECT_PAPER_SKIN       "Paper Skin"
#define ASPECT_HAEMOPHILE       "Haemophile"
#define ASPECT_GROUNDBREAKER    "Groundbreaker"
#define ASPECT_PROSPECTOR       "Prospector"
#define ASPECT_HANDYMAN         "Handyman"
#define ASPECT_FIRSTAID         "First Responder"
#define ASPECT_SAWBONES         "Sawbones"
#define ASPECT_GUNSMITH         "Gunsmith"
#define ASPECT_MARKSMAN         "Marksman"
#define ASPECT_DUALWIELD        "Guns Akimbo"
#define ASPECT_BASICGUNS        "Person of Caliber"
#define ASPECT_HACKER           "Hackerman"
#define ASPECT_COMPANYMAN       "Company Man"
#define ASPECT_JUNKIE           "Junkie"
#define ASPECT_GREENTHUMB       "Green Thumb"
#define ASPECT_NINJA            "Ninja"
#define ASPECT_TRIBAL           "Tribal"

// Combat aspects
#define ASPECT_WRESTLER         "Wrestler"
#define ASPECT_BRAWLER          "Brawler"
#define ASPECT_GUNPLAY          "Gunslinger"
#define ASPECT_TASER            "Pacifier"
#define ASPECT_SPRAY            "Trigger Happy"

// Skill aspects.
#define ASPECT_DIAGNOSTICIAN    "Diagnostician"
#define ASPECT_BUILDER          "Construction Worker"
#define ASPECT_EXOSUIT_PILOT    "Exosuit Pilot"
#define ASPECT_EXOSUIT_TECH     "Exosuit Technician"
#define ASPECT_JOGGER           "Jogger"
#define ASPECT_DAREDEVIL        "Daredevil"
