#define BAN_ANTAG list("Antag")
#define BAN_ERT list("ERT")
#define BAN_ROBOT list("Robot")
#define BAN_MAINTDRONE list("MAINTDRONE") + BAN_ROBOT
#define BAN_ANIMAL list("ANIMAL")
#define BAN_ANTAGHUD list("AntagHUD")
#define BAN_AI list("AI")
#define BAN_PAI list("pAI")
#define BAN_RECORDS list("Records")
#define BAN_GRAFFITI list("Graffiti")
#define BAN_OFFSTATION list("Offstation Roles")
#define BAN_AGITATOR list(MODE_MISC_AGITATOR)
