// BYOND lower-cases color values, and thus we do so as well to ensure atom.color == COLOR_X will work correctly
#define COLOR_BLACK            "#000000"
#define COLOR_NAVY_BLUE        "#000080"
#define COLOR_GREEN            "#008000"
#define COLOR_DARK_GRAY        "#404040"
#define COLOR_MAROON           "#800000"
#define COLOR_PURPLE           "#800080"
#define COLOR_VIOLET           "#9933ff"
#define COLOR_OLIVE            "#808000"
#define COLOR_BROWN_ORANGE     "#824b28"
#define COLOR_DARK_ORANGE      "#b95a00"
#define COLOR_GRAY40           "#666666"
#define COLOR_GRAY20           "#333333"
#define COLOR_GRAY15           "#151515"
#define COLOR_SEDONA           "#cc6600"
#define COLOR_DARK_BROWN       "#917448"
#define COLOR_BLUE             "#0000ff"
#define COLOR_DEEP_SKY_BLUE    "#00e1ff"
#define COLOR_LIME             "#00ff00"
#define COLOR_CYAN             "#00ffff"
#define COLOR_TEAL             "#33cccc"
#define COLOR_RED              "#ff0000"
#define COLOR_PINK             "#ff00ff"
#define COLOR_PALE_PINK        "#bf89ba"
#define COLOR_ORANGE           "#ff9900"
#define COLOR_YELLOW           "#ffff00"
#define COLOR_YELLOW_GRAY      "#c9a344"
#define COLOR_PALE_YELLOW      "#c1bb7a"
#define COLOR_WARM_YELLOW      "#b3863c"
#define COLOR_GRAY             "#808080"
#define COLOR_RED_GRAY         "#aa5f61"
#define COLOR_BROWN            "#b19664"
#define COLOR_GREEN_GRAY       "#8daf6a"
#define COLOR_DARK_GREEN_GRAY  "#54654c"
#define COLOR_BLUE_GRAY        "#6a97b0"
#define COLOR_DARK_BLUE_GRAY   "#3e4855"
#define COLOR_SURGERY_BLUE     "#e0f2f6"
#define COLOR_SUN              "#ec8b2f"
#define COLOR_PURPLE_GRAY      "#a2819e"
#define COLOR_BLUE_LIGHT       "#33ccff"
#define COLOR_RED_LIGHT        "#ff3333"
#define COLOR_BEIGE            "#ceb689"
#define COLOR_BABY_BLUE        "#89cff0"
#define COLOR_PALE_GREEN_GRAY  "#aed18b"
#define COLOR_PALE_RED_GRAY    "#cc9090"
#define COLOR_PALE_PURPLE_GRAY "#bda2ba"
#define COLOR_PALE_BLUE_GRAY   "#8bbbd5"
#define COLOR_LUMINOL          "#66ffff"
#define COLOR_SILVER           "#c0c0c0"
#define COLOR_GRAY80           "#cccccc"
#define COLOR_OFF_WHITE        "#eeeeee"
#define COLOR_WHITE            "#ffffff"
#define COLOR_GOLD             "#ffcc33"
#define COLOR_CLOSET_GOLD      "#6d6133"
#define COLOR_NT_RED           "#9d2300"
#define COLOR_BOTTLE_GREEN     "#1f6b4f"
#define COLOR_PALE_BTL_GREEN   "#57967f"
#define COLOR_GUNMETAL         "#545c68"
#define COLOR_WALL_GUNMETAL    "#353a42"
#define COLOR_STEEL            "#a8b0b2"
#define COLOR_MUZZLE_FLASH     "#ffffb2"
#define COLOR_CHESTNUT         "#996633"
#define COLOR_BEASTY_BROWN     "#663300"
#define COLOR_WHEAT            "#ffff99"
#define COLOR_CYAN_BLUE        "#3366cc"
#define COLOR_LIGHT_CYAN       "#66ccff"
#define COLOR_PAKISTAN_GREEN   "#006600"
#define COLOR_SOL              "#436b8e"
#define COLOR_AMBER            "#ffbf00"
#define COLOR_COMMAND_BLUE     "#46698c"
#define COLOR_SKY_BLUE         "#5ca1cc"
#define COLOR_PALE_ORANGE      "#b88a3b"
#define COLOR_CIVIE_GREEN      "#b7f27d"
#define COLOR_TITANIUM         "#d1e6e3"
#define COLOR_DARK_GUNMETAL    "#4c535b"
#define COLOR_BRONZE           "#8c7853"
#define COLOR_BRASS            "#b99d71"
#define COLOR_INDIGO           "#4b0082"
#define COLOR_ALUMINIUM        "#bbbbbb"
#define COLOR_CRYSTAL          "#00c8a5"
#define COLOR_ASTEROID_ROCK    "#735555"
#define COLOR_NULLGLASS        "#ff6088"
#define COLOR_DIAMOND          "#d8d4ea"
#define COLOR_VOX			   "#244238"


#define	PIPE_COLOR_GREY        "#808080"
#define	PIPE_COLOR_RED         "#ff0000"
#define	PIPE_COLOR_BLUE        "#0000ff"
#define	PIPE_COLOR_CYAN        "#00ffff"
#define	PIPE_COLOR_GREEN       "#00ff00"
#define	PIPE_COLOR_YELLOW      "#ffcc00"
#define	PIPE_COLOR_BLACK       "#444444"
#define	PIPE_COLOR_ORANGE      "#b95a00"
#define PIPE_COLOR_WHITE       "#ffffff"

#define	COMMS_COLOR_DEFAULT    "#ff00ff"
#define	COMMS_COLOR_ENTERTAIN  "#666666"
#define	COMMS_COLOR_AI         "#ff00ff"
#define	COMMS_COLOR_COMMON     "#408010"
#define COMMS_COLOR_HAILING    "#cc00aa"
#define	COMMS_COLOR_SERVICE    "#709b00"
#define	COMMS_COLOR_SUPPLY     "#7f6539"
#define	COMMS_COLOR_SCIENCE    "#993399"
#define	COMMS_COLOR_MEDICAL    "#009190"
#define	COMMS_COLOR_MEDICAL_I  "#509190"
#define	COMMS_COLOR_EXPLORER   "#929820"
#define	COMMS_COLOR_ENGINEER   "#a66300"
#define	COMMS_COLOR_SECURITY   "#930000"
#define	COMMS_COLOR_SECURITY_I "#935050"
#define	COMMS_COLOR_COMMAND    "#204090"
#define	COMMS_COLOR_CENTCOMM   "#5c5c7c"
#define	COMMS_COLOR_SYNDICATE  "#6d3f40"
#define	COMMS_COLOR_SKRELL     "#7331c4"
#define COMMS_COLOR_VOX        "#f32b06"
#define COMMS_COLOR_BEARCAT    "#590e2d"
#define COMMS_COLOR_COLONY     "#ceaf3e"
#define COMMS_COLOR_VERNE      "#738465"

#define WOOD_COLOR_GENERIC     "#d5a66e"
#define WOOD_COLOR_RICH        "#792f27"
#define WOOD_COLOR_PALE        "#d2bc9d"
#define WOOD_COLOR_PALE2       "#e6d2ba"
#define WOOD_COLOR_BLACK       "#332521"
#define WOOD_COLOR_CHOCOLATE   "#543c30"
#define WOOD_COLOR_YELLOW      "#e3994e"

#define GLASS_COLOR            "#aaccff"
#define GLASS_COLOR_PHORON     "#7c3a9a"
#define GLASS_COLOR_TINTED     "#222222"
#define GLASS_COLOR_FROSTED    "#eeeeee"

#define COLOR_BLOOD_HUMAN      "#a10808"

//Color defines used by the assembly detailer.
#define COLOR_ASSEMBLY_BLACK   "#545454"
#define COLOR_ASSEMBLY_BGRAY   "#9497ab"
#define COLOR_ASSEMBLY_WHITE   "#e2e2e2"
#define COLOR_ASSEMBLY_RED     "#cc4242"
#define COLOR_ASSEMBLY_ORANGE  "#e39751"
#define COLOR_ASSEMBLY_BEIGE   "#af9366"
#define COLOR_ASSEMBLY_BROWN   "#97670e"
#define COLOR_ASSEMBLY_GOLD    "#aa9100"
#define COLOR_ASSEMBLY_YELLOW  "#ceca2b"
#define COLOR_ASSEMBLY_GURKHA  "#999875"
#define COLOR_ASSEMBLY_LGREEN  "#789876"
#define COLOR_ASSEMBLY_GREEN   "#44843c"
#define COLOR_ASSEMBLY_LBLUE   "#5d99be"
#define COLOR_ASSEMBLY_BLUE    "#38559e"
#define COLOR_ASSEMBLY_PURPLE  "#6f6192"

//Colors defines used by e-sword lighting
#define COLOR_SABER_BLUE       "#40ceff"
#define COLOR_SABER_RED        "#ff0000"	//In case someone wants to tweak COLOR_RED, since COLOR_GREEN is not #00ff00
#define COLOR_SABER_GREEN      "#00ff00"
#define COLOR_SABER_PURPLE     "#6800f4"
#define COLOR_SABER_SKRELL     "#6600cc"
#define COLOR_SABER_AXE        "#00ccff"
#define COLOR_SABER_CUTLASS    "#ff0033"

// Used by fluid system.
#define COLOR_OCEAN "#99f5ff"

// Used to easily change research colour in case of ???
#define COLOR_RESEARCH COLOR_PURPLE_GRAY

//Blob colors
#define BLOB_COLOR_CORE      "#c96e28"
#define BLOB_COLOR_SHIELD    "#9ed659"
#define BLOB_COLOR_RAV       "#d65f42"
#define BLOB_COLOR_PULS      "#b5ff5b"

#define RANDOM_RGB rgb(rand(0,255), rand(0,255), rand(0,255))

// Codex category colours.
#define CODEX_COLOR_LORE      "#abdb9b"
#define CODEX_COLOR_MECHANICS "#9ebcd8"
#define CODEX_COLOR_ANTAG     "#e5a2a2"

#define COLOR_WEBHOOK_DEFAULT 0x8bbbd5

#define COLOR_DARKMODE_BACKGROUND "#202020"
#define COLOR_DARKMODE_DARKBACKGROUND "#171717"
#define COLOR_DARKMODE_TEXT "#a4bad6"

//colors for holoplants //from infinity
#define COLOR_LIGHTING_RED_BRIGHT		"#aa2733"
#define COLOR_LIGHTING_GREEN_BRIGHT		"#8aa88a"
#define COLOR_LIGHTING_BLUE_BRIGHT		"#8a95a8"
#define COLOR_LIGHTING_ORANGE_BRIGHT	"#d7be93"
#define COLOR_LIGHTING_PURPLE_BRIGHT	"#aa2799"
#define COLOR_LIGHTING_CYAN_BRIGHT		"#67c1b6"
