
#define AUTHORITY_LEVEL_INNIE -1
#define AUTHORITY_LEVEL_CIV 1
#define AUTHORITY_LEVEL_UNSC 2
#define AUTHORITY_LEVEL_ONI 3

#define ALL_AUTHORITY_LEVELS list(\
AUTHORITY_LEVEL_INNIE,\
AUTHORITY_LEVEL_CIV,\
AUTHORITY_LEVEL_UNSC,\
AUTHORITY_LEVEL_ONI,\
)
