#define LANGUAGE_ENGLISH    "English"
#define LANGUAGE_MANDARIN   "Mandarin"
#define LANGUAGE_GERMAN     "German"
#define LANGUAGE_FRENCH     "French"
#define LANGUAGE_SPANISH    "Spanish"
#define LANGUAGE_ITALIAN    "Italian"
#define LANGUAGE_TURKISH    "Turkish"
#define LANGUAGE_INDONESIAN "Indonesian"
#define LANGUAGE_SWEDISH    "Swedish"
#define LANGUAGE_DANISH     "Danish"
#define LANGUAGE_NORWEGIAN  "Norwegian"
#define LANGUAGE_ICELANDIC  "Icelandig"
#define LANGUAGE_FINNISH    "Finnish"
#define LANGUAGE_JAPANESE   "Japanese"

#define LANGUAGE_SANGHEILI  "Sangheili"
#define LANGUAGE_LEKGOLO    "Lekgolo"
#define LANGUAGE_FLOODMIND  "Floodmind"
#define LANGUAGE_UNGGOY     "Balahese"
#define LANGUAGE_KIGYAR     "Ruuhti"
#define LANGUAGE_BRUTE      "Doisacci"
#define LANGUAGE_SANSHYUUM  "Janjur Qomi"
#define LANGUAGE_TVOAI      "T\'voai"
#define LANGUAGE_YANMEE_HIVE "Yanme e Hivemind"
