#define LANGUAGE_ENGLISH    "English"
#define LANGUAGE_MANDARIN   "Mandarin"
#define LANGUAGE_GERMAN     "German"
#define LANGUAGE_FRENCH     "French"
#define LANGUAGE_SPANISH    "Spanish"
#define LANGUAGE_ITALIAN    "Italian"
#define LANGUAGE_TURKISH    "Turkish"
#define LANGUAGE_INDONESIAN "Indonesian"
#define LANGUAGE_SWEDISH    "Swedish"
#define LANGUAGE_DANISH     "Danish"
#define LANGUAGE_NORWEGIAN  "Norwegian"
#define LANGUAGE_ICELANDIC  "Icelandig"
#define LANGUAGE_FINNISH    "Finnish"
#define LANGUAGE_JAPANESE   "Japanese"

#define LANGUAGE_SANGHEILI  "Sangheili"
#define LANGUAGE_LEKGOLO    "Lekgolo"
