#define TURF_REMOVE_CROWBAR     1
#define TURF_REMOVE_SCREWDRIVER 2
#define TURF_REMOVE_SHOVEL      4
#define TURF_REMOVE_WRENCH      8
#define TURF_REMOVE_WELDER      16
#define TURF_CAN_BREAK          32
#define TURF_CAN_BURN           64
#define TURF_HAS_EDGES          128
#define TURF_HAS_CORNERS        256
#define TURF_IS_FRAGILE         512
#define TURF_ACID_IMMUNE        1024