
/datum/map/geminus_city
	allowed_jobs = list(\
		/datum/job/unsc/spartan_two,\
		/datum/job/unsc/crew,\
		/datum/job/unsc/medical,\
		/datum/job/unsc/marine,\
		/datum/job/unsc/marine/specialist,\
		/datum/job/unsc/marine/squad_leader,\
		/datum/job/unsc/odst,\
		/datum/job/unsc/odst/squad_leader,\
		/datum/job/unsc/commanding_officer,\
		/datum/job/unsc/executive_officer,\
		/datum/job/unsc/oni/research,\
		/datum/job/unsc/oni/research/director,\
		/datum/job/unsc_ai,\
		/datum/job/colonist,\
		/datum/job/geminus_innie,\
		/datum/job/geminus_innie/officer,\
		/datum/job/geminus_innie/commander,\
		/datum/job/geminus_x52/researcher,\
		/datum/job/geminus_x52/research_director,\
		/datum/job/soe_commando,\
		/datum/job/soe_commando_officer,\
		/datum/job/soe_commando_captain,\
		/datum/job/geminus_innie/orion_defector,\
		/datum/job/insurrectionist_ai,\
		/datum/job/covenant/AI,\
		/datum/job/covenant/huragok,\
		/datum/job/covenant/sangheili_minor,\
		/datum/job/covenant/sangheili_major,\
		/datum/job/covenant/sangheili_honour_guard,\
		/datum/job/covenant/sangheili_ultra,\
		/datum/job/covenant/sangheili_shipmaster,\
		/datum/job/covenant/kigyarminor,\
		/datum/job/covenant/unggoy_minor,
		/datum/job/covenant/unggoy_major,\
		/datum/job/covenant/unggoy_ultra,\
		/datum/job/covenant/unggoy_deacon,\
		/datum/job/covenant/unggoy_heavy,\
		/datum/job/covenant/skirmmurmillo,\
		/datum/job/covenant/skirmcommando,\
		/datum/job/covenant/skirmchampion,\
		/datum/job/covenant/brute_minor,\
		/datum/job/covenant/brute_major,\
		/datum/job/covenant/brute_captain,\
		/datum/job/covenant/yanmee_minor,\
		/datum/job/covenant/yanmee_major,\
		/datum/job/covenant/yanmee_ultra,\
		/datum/job/covenant/yanmee_leader,\
		/datum/job/covenant/lesser_prophet,\
		/datum/job/covenant/mgalekgolo\
		)
