#define SURGERY_NO_ROBOTIC        1
#define SURGERY_NO_CRYSTAL        2
#define SURGERY_NO_STUMP          4
#define SURGERY_NO_FLESH          8 
#define SURGERY_NEEDS_INCISION   16
#define SURGERY_NEEDS_RETRACTED  32
#define SURGERY_NEEDS_ENCASEMENT 64
