
// Black cards.
/obj/item/weapon/deck/cah/black/card_text_list = list(
    "Why am I itchy?",
    "Who the FUCK stole the goddamn spare ID?",
    "Who won the Spaceball Supreme Championship?",
    "What happened on the away mission?",
    "Why did the deck officer run into maint?",
    "Today, MPs shot ____.",
    "The Chaplain this shift is worshiping _____.",
    "What is the merchant selling today?",
    "Cargo ordered a crate full of _____.",
    "An ERT was called due to ______.",
    "Alert! The CO has armed themselves with _____.",
    "Current Laws: ________ is your master.",
    "Current Laws: ________ is the enemy.",
    "_____ vented the entirety of Cargo.",
    "Today, science found an anomaly that made people ____ and ____.",
    "Attention: Level 7 _____ detected. All personnel must contain the outbreak.",
    "The EC's new rank will be an officer in charge of ____.",
    "The marines like to _____ in their off-time.",
    "A fleet doctor always enjoys ______.",
    "There was a rap battle between ____ and ____.",
    "Caution, ______ have been detected in collision course with the ship.",
    "Today's kitchen menu includes _______.",
    "What did the mercenaries want when they attacked the ship?",
    "I think the CO is insane. He just demanded ______ in his office.",
    "Fuckin' scientists, they just turned Misc. Research into _______ .",
    "What's my fetish?",
    "Hello, _______ here with _______",
    "No one else was at _______, they wouldn't understand the ______",
    "What's in the vault?",
    "We found an anomaly that generates infinite _____!",
    "Why am I shivering?",
    "What is this world coming to? First, ________, now _______",
    "NanoTrasen's labor union decided to use _______ to raise employee morale.",
    "The roboticist just invented an artificial _____!",
    "The Chemist's drug of choice is ______",
    "It is common practice for _______ to ______ on Moghes.",
    "Mercurial Colonies are _____.",
    "The Skrell are celebrating _____ today.",
    "_____ is/are why I'm afraid of the maintenance tunnels.",
    "_____ used ____ to create their newest invention, _____!",
    "Scientists are not allowed to make Gatling _____.",
    "It's not a party until the ____ arrive.",
    "The Unathi janitor is currently murdering _____",
    "No matter how many Tajara you have, _____ is never acceptable.",
    "No, the AI's first law is NOT to serve _____.",
    "The chef is serving _____ made of _____",
    "A stowaway has been given a job opportunity, and is now managing _____",
    "So, how are we going to nuke the ship today?",
    "The robots are not disposal bins for your _____.",
    "You can never have too many _____ on shift.",
    "Today's away mission will lead _____ towards _____",
    "An infinite number of monkies want to talk to us about the script of _____ they wrote!",
    "High levels of _____ _____ detected on ship. Please report to medbay if you're feeling strange.",
    "If you're a robot, the first thing you do is _____ the _____.",
    "No _____ _____ on the ship.",
    "SolGov keeps spending too much on _____ and too little on _____.",
    "Alert! _____ has escaped containment in the Xenobiology Lab!",
    "Due to abuse by the EC, the CO has decided that ______ is now against regulations.",
    "Bioscans indicate that _____ have been breeding in _____. Clear them out, before this starts to affect productivity.",
    "SolGov officials would like to congratulate _____ on their promotion to ______",
    "The MPs arrested the _____ for distributing contraband _____.",
    "Tune your camera monitors to the Thunderdome and watch _____ take on ______",
    "We have gone into red-alert due to an incident involving _____ shamelessly entering _____",
    "All is well with the vessel, after Engineers decided to jettison _____ using a mass driver",
    "The ship is now passing through a belt of _____. Please stay clear.",
    "The infirmary is now accepting _____ donations",
    "Independent research by Nanotrasen has revealed that _____ has an adverse effect on the productivity of Nanotrasen employees",
    "The psychiatrist, overjoyed at the thought of somebody finally coming to visit them, was disappointed to see that all that was in front of his door was just ____",
    "A merchant ship has docked, but is only selling ____ and _____",
    "The bartender is now serving drinks made of pure liquified ____.",
    "NanoTrasen just bought out SolGov's ____ division",
    "We just encountered a species that consists entirely of _____.",
    "The Free Trade Union just put sanctions on selling ____ to ____.",
    "The Marines, to prove their superiority over the Fleet, are now holding training exercises fighting against _____.",
    "The Fleet's new ship is named the SFV _____.",
    "The latest EC gear: duct-taping _____ to your back.",
    "______! An alcoholic marine's favorite beverage!",
    "ATTENTION: New Command Report Created.  All _____ are enemies of SCG.",
    "The Positronic Union has now developed robots that solely _____ with exreme efficiency.",
    "Thanks to downsizing, the _____ division of the EC will now be handled by contractor _____s.",
    "Unfortunately, the CO  is dead because of the actions of ___ who ___.",
    "Why has the self-destruct been activated?",
    "After flying the ship to _____, the pilot is now spending his time _____"
)