// Black cards.
/obj/item/weapon/deck/cah/black/card_text_list = list(
	"Why am I itchy?",
	"Today, Security shot ____.",
	"The Chaplain this shift is worshipping _____.",
	"Cargo ordered a crate full of _____.",
	"An ERT was called due to ______.",
	"Alert! The Station Administrator has armed themselves with _____.",
	"Current Laws: ________ is your master.",
	"Current Laws: ________ is the enemy.",
	"_____ vented the entirety of Cargo.",
	"Today, science found an anomaly that made people ____ and ____.",
	"There was a rap battle between ____ and ____.",
	"Caution, ______ have been detected in collision course with the station.",
	"Today's kitchen menu includes _______.",
	"What did the mercenaries want when they attacked the station?",
	"I think the Station Administrator is insane. He just demanded ______ in his office.",
	"Fuckin' scientists, they just turned Misc. Research into _______ .",
	"What's my fetish?",
	"Hello, _______ here with _______",
	"No one else was at _______, they wouldn't understand the ______",
	"Why am I shivering?",
	"What is this world coming to? First, ________, now _______",
	"NanoTrasen's labor union decided to use _______ to raise employee morale.",
	"The Chemist's drug of choice is ______",
	"It is common practice for _______ to ______ on Moghes.",
	"Mercurial Colonies are _____.",
	"The Skrell are celebrating _____ today.",
	"_____ is/are why I'm afraid of the maintenance tunnels.",
	"_____ used ____ to create their newest invention, _____!",
	"Scientists are not allowed to make Gatling _____.",
	"It's not a party until the ____ arrive.",
	"No matter how many Tajara you have, _____ is never acceptable.",
	"No, the AI's first law is NOT to serve _____.",
	"The robots are not disposal bins for your _____.",
	"You can never have too many _____ on shift.",
	"Command Alert! _____ has boarded the station!",
	"An Emergency Response Team was dispatched last shift due to _____.",
	"I hear Central's adding a vending machine for ____",
	"____. I bet somebody tries to fuck it.",
	"Purge the ____!",
	"We found ____ in the dorm rooms with ____.",
	"Crew, I must inform you that ____ has died from ____.",
	"The station is now entering a ____ shower.",
	"R&D has artificially recreated ____!",
	"If I had to, I'd choose death by ____.",
	"Not even absinthe could could wipe away the memory of ____.",
	"A dick only ____ could love.",
	"Medbay has abandoned traditional practices and is experimenting with ____.",
	"Something in the dorms sounds like ____.",
	"Someone requested a custom job title of ____.",
	"Everyone knows Tajara love ____.",
	"What's the virologist passing out?",
	"What did the chemist just spray me with?",
	"____ Station 13.",
	"Security was never the same after they had to deal with ____.",
	"What broke into the Captain's office?",
	"I dare you to try ____.",
	"____. Not even once.",
	"Bloody hell, Xenoarcheology dug up ____.",
	"Once, I walked into the shower room and saw ___.",
	"Once, on an empty shift, I ran into ____.",
	"Personally, when I get lewd, I like to think about ____.",
	"What's a guaranteed way to turn me on?",
	"What don't you want to find in your Donk Pockets?",
	"What does NanoTrasen hate the most?",
	"Gibson Gazette reveals an exclusive story on ____!",
	"Luck? No,that was ____.",
	"The chef is making meat out of ____.",
	"The shuttle was called due to ____.",
	"As I fell asleep, I swear I heard people whispering about ____."
	)
