// White cards.
/obj/item/weapon/deck/cah/var/list/card_text_list = list(
	"Those motherfucking carp",
	"Having sex in the maintenance tunnels",
	"Space 'Nam",
	"Space lesbians",
	"The Gardener getting SUPER high",
	"The Station Administrator thinking they're a badass",
	"Being in a cult",
	"Racially biased lawsets",
	"An Unathi who WON'T STOP FIGHTING",
	"Tajara fetishists",
	"Bald thirty-year-olds",
	"A Chief Engineer who can't setup the engine",
	"Being sucked out into space",
	"Officer Beepsky",
	"Engineering",
	"The grey tide.",
	"The Research Director",
	"Fucking synths",
	"Man-eating purple pod plants",
	"Chemical sprayers filled with lube",
	"Librarians",
	"Squids",
	"Cats",
	"Lizards",
	"Apes",
	"Trees",
	"Supermatter undergarments",
	"Bluespace",
	"Five hundred rabid spiders",
	"Five hundred rabid diona nymphs",
	"Cable ties",
	"Rampant vending machines",
	"Positronic drink coasters",
	"Kitchen utensil anomalies",
	"Locked lockers",
	"Energy spatulas",
	"Flashbang gauntlets",
	"Carp",
	"Space whales",
	"Blu-sharks",
	"Fax machines",
	"Exquisite Pens",
	"Dr. Maxman's male enhancements",
	"Gyrating slimes",
	"Forehead-mounted laser weaponry",
	"Pelvis-mounted laser weaponry",
	"Cardboard cutouts",
	"An obscene amount of rubber ducks",
	"Brain cakes",
	"A drone's game of life.",
	"Anomaly suits",
	"A gardener smoking reishi",
	"Military-grade baseball bats",
	"Barricading the bar",
	"An irritatingly chipper robot",
	"Androids hanging out in the bar drinking beer",
	"Gear harnesses",
	"A seventeen-year-old Station Administrator",
	"The throbbing erection that the HoS gets at the thought of shooting something",
	"Trying to stab someone and hugging them instead",
	"Waking up naked in the maintenance tunnels",
	"Horrible cloning accidents",
	"Licking the supermatter due to a dare",
	"A Quartermaster who WON'T STOP ordering guns",
	"Teaching a synthetic the Birds and the Bees",
	"Unnecessary surgery",
	"My addiction to spiders",
	"wetskrell.nt",
	"DOCTOR MAXMAN!",
	"A group of Skrell getting their squish on",
	"Enough soporific to put the entire station down",
	"Delicious Vietnamese cuisine",
	"Approximately 500 units of absinthe",
	"Outdated 21st century references",
	"Hacking the mulebots",
	"Sex in the captain's bed",
	"Girls with secret dongs",
	"Sauna shifts",
	"Pestering R&D for nanopaste",
	"Femboys in space",
	"Setting up a brothel in the old bar",
	"Lewding a borg",
	"Three Teshari, all at once",
	"Lady sneks",
	"Bees?",
	"Blast Hardcheese",
	"Station-wide orgies",
	"Vore",
	"My foot fetish",
	"Lewdness",
	"A particularly useless engineer",
	"The Chain of Command",
	"Puritanism",
	"Having so many genemods you're not even recognizable as a human being",
	"Tailsex",
	"Space bitches",
	"The Captain's private chambers",
	"A Teshari with a cap on its head",
	"Akula blowjobs",
	"Cuddling",
	"The delaminating supermatter crystal",
	"Towel whips",
	"A syringe gun loaded with LSD",
	"Catgirls",
	"A suspicious amount of women",
	"Hacking the XXXVend",
	"Filling the IAA's briefcase with sex toys when they're not looking",
	"Voluptuousness",
	"Rerouting disposals to the Captain's office",
	"Liver damage",
	"Thunder thighs",
	"Teshari hairstyles",
	"Drunk Akula",
	"Pettings",
	"An inferior bartender",
	"Foreskin",
	"Lamia tails",
	"Double dicks",
	"Nanotrasen's safety standards",
	"Lewd spiders",
	"Bike horns",
	"Pun-Pun's throbbing erection",
	"An entire shuttle full of bike horns",
	"Sabotaging SMES units for entertainment",
	"Getting hit in the face with a horse dildo",
	"Ungodly genetic hybrids",
	"HONK",
	"Blatant violations of Asiimov's laws",
	"A scenic tour of the disposal chute",
	"A voyeuristic AI",
	"Disabling the cameras in the dorms",
	"Lewdism",
	"Daddy issues",
	"Knots",
	"Shark tits",
	"Non-prescription glasses",
	"Slimes that taste like strawberry jam",
	"Thigh-highs",
	"Ritual sacrifice",
	"Shooting virgins out of the mass driver",
	"Indecent proposals before you leave arrivals",
	"A Getamore bar floating in the pool",
	"Security tracking assistant gibs down the hall",
	"The lack of STDs",
	"Boot-knives",
	"The Fuckzone",
	"Anti-lewd spiders",
	"Public ERP",
	"wetterskrell.nt",
	"A surprisingly erotic Xenomorph"
	)
