#include "_map_include.dm"

#include "example\example_define.dm" // Always included because tests. May be fixable later.

#include "using.dm"

#include "antag_spawn\antag_spawn_bases.dm"
#include "antag_spawn\ert\ert.dm"
#include "antag_spawn\heist\heist.dm"
#include "antag_spawn\mercenary\mercenary.dm"
#include "antag_spawn\ninja\ninja.dm"
#include "antag_spawn\vox\voxraider.dm"
#include "antag_spawn\wizard\wizard.dm"

#include "away\away_sites.dm"
#include "away_sites_testing\away_sites_testing_define.dm"
#include "random_ruins\exoplanet_ruins\exoplanet_ruins.dm"
#include "random_ruins\exoplanet_ruins\crashed_pod\crashed_pod.dm"
#include "random_ruins\exoplanet_ruins\datacapsule\datacapsule.dm"
#include "random_ruins\exoplanet_ruins\deserted_lab\deserted_lab.dm"
#include "random_ruins\exoplanet_ruins\drill_site\drill_site.dm"
#include "random_ruins\exoplanet_ruins\fountain\fountain_ruin.dm"
#include "random_ruins\exoplanet_ruins\hut\hut.dm"
#include "random_ruins\exoplanet_ruins\hydrobase\hydrobase.dm"
#include "random_ruins\exoplanet_ruins\icarus\icarus.dm"
#include "random_ruins\exoplanet_ruins\lodge\lodge.dm"
#include "random_ruins\exoplanet_ruins\marooned\marooned.dm"
#include "random_ruins\exoplanet_ruins\monoliths\monoliths.dm"
#include "random_ruins\exoplanet_ruins\oasis\oasis.dm"
#include "random_ruins\exoplanet_ruins\oldlab\oldlab.dm"
#include "random_ruins\exoplanet_ruins\oldlab2\oldlab2.dm"
#include "random_ruins\exoplanet_ruins\oldpod\oldpod.dm"
#include "random_ruins\exoplanet_ruins\playablecolony\playablecolony.dm"
#include "random_ruins\exoplanet_ruins\playablecolony2\playablecolony2.dm"
#include "random_ruins\exoplanet_ruins\radshrine\radshrine.dm"
#include "random_ruins\exoplanet_ruins\spider_nest\spider_nest.dm"
#include "random_ruins\exoplanet_ruins\tar_anomaly\tar_anomaly.dm"
#include "random_ruins\exoplanet_ruins\trash_heap\trash_heap.dm"
#include "random_ruins\space_ruins\space_ruins.dm"
#include "~mapsystem\map_preferences.dm"
#include "~mapsystem\map_ranks.dm"
#include "~mapsystem\maps.dm"
#include "~mapsystem\maps_announcements.dm"
#include "~mapsystem\maps_areas.dm"
#include "~mapsystem\maps_jobs.dm"
#include "~mapsystem\maps_unit_testing.dm"
#include "~unit_tests\unit_testing.dm"
