/datum/species/human
	extended_cultural_info = list(
		TAG_CULTURE = list(
			CULTURE_HUMAN_AVACOMMON, 
			CULTURE_HUMAN_AVANOBLE,
			CULTURE_HUMAN_LORRIMAN,
			CULTURE_HUMAN_LORDUP,
			CULTURE_HUMAN_LORDLOW,
			CULTURE_HUMAN_MIRANIAN, 
			CULTURE_HUMAN_NYXIAN
		),
		TAG_FACTION = list(
			FACTION_SOL_CENTRAL,
			FACTION_FLEET,
			FACTION_EXPEDITIONARY,
			FACTION_INDIE_CONFED,
			FACTION_NANOTRASEN,
			FACTION_FREETRADE,
			FACTION_CORPORATE,
			FACTION_HEPHAESTUS,
			FACTION_XYNERGY,
			FACTION_DAIS,
			FACTION_ZENG_HU,
			FACTION_WARD_TAKAHASHI,
			FACTION_GRAYSON,
			FACTION_AERTHER,
			FACTION_MAJOR_BILL,
			FACTION_FOCAL_POINT,
			FACTION_XION,
			FACTION_VEY_MED,
			FACTION_BISHOP,
			FACTION_SEPTENERGO,
			FACTION_PCRC,
			FACTION_SAARE,
			FACTION_ZPCI,
			FACTION_OTHER
		),
		TAG_HOMEWORLD = list(
			HOME_SYSTEM_EARTH,
			HOME_SYSTEM_LUNA,
			HOME_SYSTEM_MARS,
			HOME_SYSTEM_VENUS,
			HOME_SYSTEM_CERES,
			HOME_SYSTEM_PLUTO,
			HOME_SYSTEM_TAU_CETI,
			HOME_SYSTEM_HELIOS,
			HOME_SYSTEM_TERRA,
			HOME_SYSTEM_SAFFAR,
			HOME_SYSTEM_PIRX,
			HOME_SYSTEM_TADMOR,
			HOME_SYSTEM_BRAHE,
			HOME_SYSTEM_IOLAUS,
			HOME_SYSTEM_GAIA,
			HOME_SYSTEM_MAGNITKA,
			HOME_SYSTEM_CASTILLA,
			HOME_SYSTEM_FOSTER,
			HOME_SYSTEM_TERSTEN,
			HOME_SYSTEM_AVALON,
			HOME_SYSTEM_MIRANIA,
			HOME_SYSTEM_NYX_BRINKBURN,
			HOME_SYSTEM_NYX_KALDARK,
			HOME_SYSTEM_NYX_ROANOK,
			HOME_SYSTEM_NYX_YUKLIT,
			HOME_SYSTEM_NYX_CASSER,
			HOME_SYSTEM_OTHER,
			HOME_SYSTEM_DEEP_SPACE
		)
	)

/datum/species/skrell
	extended_cultural_info = list(
		TAG_FACTION = list(
			FACTION_SKRELL_MED,
			FACTION_SKRELL_FOOD
		)
	)
