// SIERRA TODO: GET RID OF IT!!!
#include "ai/_ai.dme"
#include "adherent_discharge/_adherent_discharge.dme"
#include "body_markings/_body_markings.dme"
#include "client_verbs/_client_verbs.dme"
// #include "don_loadout/_don_loadout.dme" // Не открывать до Рождества
#include "eris_announcer/_eris_announcer.dme"
#include "emote_panel/_emote_panel.dme"
#include "ex666_ecosystem/_ex666_ecosystem.dme"
#include "expanded_culture_descriptor/_expanded_culture_descriptor.dme"
#include "gliding/_gliding.dme"
#include "machinery/_machinery.dme"
#include "hairs_ports/_hairs_ports.dme"
#include "hardsuits/_hardsuits.dme"
#include "sprite_accessories/_sprite_accessories.dme"
#include "ssgunsetc/_ssgunsetc.dme"
#include "jukebox_tapes/_jukebox_tapes.dme"
#include "loadout_items/_loadout_items.dme"
#include "lobbyscreen/_lobbyscreen.dme"
#include "ipc_cooling_unit/_ipc_cooling_unit.dme"
#include "music_player/_music_player.dme"
#include "ntnet/_ntnet.dme"
#include "nyc_posters/_nyc_posters.dme"
#include "ssinput/_ssinput.dme"
#include "statusbar/_statusbar.dme"
#include "unathi/_unathi.dme"
#include "utf8/_utf8.dme"
#include "utility_items/_utility_items.dme"

#include "../packs/sierra-tweaks/_pack.dm"
