/datum/trader/ship/gunshop
	possible_trading_items = list(
		/obj/item/gun/projectile/pistol/holdout = TRADER_ALL,
		/obj/item/gun/projectile/pistol/bobcat = TRADER_ALL,
		/obj/item/gun/projectile/pistol/optimus = TRADER_ALL,
		/obj/item/gun/projectile/pistol/m22f = TRADER_ALL,
		/obj/item/gun/projectile/pistol/m19 = TRADER_ALL,
		/obj/item/gun/projectile/pistol/magnum_pistol = TRADER_ALL,
		/obj/item/gun/projectile/pistol/sec = TRADER_ALL,
		/obj/item/gun/projectile/boltloader/boltaction	= TRADER_ALL,
		/obj/item/gun/projectile/pistol/sec/MK = TRADER_BLACKLIST,
		/obj/item/gun/projectile/shotgun/pump = TRADER_SUBTYPES_ONLY,
		/obj/item/ammo_magazine = TRADER_SUBTYPES_ONLY,
		/obj/item/ammo_magazine/pistol/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/mil_rifle/heavy/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/gyrojet/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/pistol/small/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/pistol/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/box/pistol/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/box/machinegun/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/machine_pistol/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/smg_top/empty = TRADER_BLACKLIST,
		/obj/item/ammo_magazine/magnum/empty = TRADER_BLACKLIST,
		/obj/item/clothing/accessory/storage/holster = TRADER_ALL
	)
