/obj/item/weapon/reagent_containers/chem_disp_cartridge
	small
		volume = CARTRIDGE_VOLUME_SMALL

	medium
		volume = CARTRIDGE_VOLUME_MEDIUM

	// Multiple
	water		spawn_reagent = "water"
	sugar		spawn_reagent = "sugar"

	// Chemistry
	hydrazine	spawn_reagent = "hydrazine"
	lithium		spawn_reagent = "lithium"
	carbon		spawn_reagent = "carbon"
	ammonia		spawn_reagent = "ammonia"
	acetone		spawn_reagent = "acetone"
	sodium		spawn_reagent = "sodium"
	aluminum	spawn_reagent = "aluminum"
	silicon		spawn_reagent = "silicon"
	phosphorus	spawn_reagent = "phosphorus"
	sulfur		spawn_reagent = "sulfur"
	hclacid		spawn_reagent = "hclacid"
	potassium	spawn_reagent = "potassium"
	iron		spawn_reagent = "iron"
	copper		spawn_reagent = "copper"
	mercury		spawn_reagent = "mercury"
	radium		spawn_reagent = "radium"
	ethanol		spawn_reagent = "ethanol"
	sacid		spawn_reagent = "sacid"
	tungsten	spawn_reagent = "tungsten"

	// Bar, alcoholic
	beer		spawn_reagent = "beer"
	kahlua		spawn_reagent = "kahlua"
	whiskey		spawn_reagent = "whiskey"
	wine		spawn_reagent = "wine"
	vodka		spawn_reagent = "vodka"
	gin			spawn_reagent = "gin"
	rum			spawn_reagent = "rum"
	tequila		spawn_reagent = "tequilla"
	vermouth	spawn_reagent = "vermouth"
	cognac		spawn_reagent = "cognac"
	ale			spawn_reagent = "ale"
	mead		spawn_reagent = "mead"

	// Bar, soft
	ice			spawn_reagent = "ice"
	coffee		spawn_reagent = "coffee"
	cream		spawn_reagent = "cream"
	tea			spawn_reagent = "tea"
	icetea		spawn_reagent = "icetea"
	cola		spawn_reagent = "cola"
	smw			spawn_reagent = "spacemountainwind"
	dr_gibb		spawn_reagent = "dr_gibb"
	spaceup		spawn_reagent = "space_up"
	tonic		spawn_reagent = "tonic"
	sodawater	spawn_reagent = "sodawater"
	lemon_lime	spawn_reagent = "lemon_lime"
	orange		spawn_reagent = "orangejuice"
	lime		spawn_reagent = "limejuice"
	watermelon	spawn_reagent = "watermelonjuice"

	// ERT
	inaprov		spawn_reagent = "inaprovaline"
	ryetalyn	spawn_reagent = "ryetalyn"
	paracetamol	spawn_reagent = "paracetamol"
	tramadol	spawn_reagent = "tramadol"
	oxycodone	spawn_reagent = "oxycodone"
	sterilizine	spawn_reagent = "sterilizine"
	leporazine	spawn_reagent = "leporazine"
	kelotane	spawn_reagent = "kelotane"
	dermaline	spawn_reagent = "dermaline"
	dexalin		spawn_reagent = "dexalin"
	dexalin/small	volume = CARTRIDGE_VOLUME_SMALL // For the medicine cartridge crate, so it's not too easy to get large amounts of dexalin
	dexalin_p	spawn_reagent = "dexalinp"
	tricord		spawn_reagent = "tricordrazine"
	dylovene	spawn_reagent = "anti_toxin"
	synaptizine	spawn_reagent = "synaptizine"
	hyronalin	spawn_reagent = "hyronalin"
	arithrazine	spawn_reagent = "arithrazine"
	alkysine	spawn_reagent = "alkysine"
	imidazoline	spawn_reagent = "imidazoline"
	peridaxon	spawn_reagent = "peridaxon"
	bicaridine	spawn_reagent = "bicaridine"
	hyperzine	spawn_reagent = "hyperzine"
	rezadone	spawn_reagent = "rezadone"
	spaceacillin	spawn_reagent = "spaceacillin"
	ethylredox	spawn_reagent = "ethylredoxrazine"
	sleeptox	spawn_reagent = "stoxin"
	chloral		spawn_reagent = "chloralhydrate"
	cryoxadone	spawn_reagent = "cryoxadone"
	clonexadone	spawn_reagent = "clonexadone"
