
#include "mode_stranded.dm"
#include "evac_pelican.dm"
#include "materials.dm"
#include "misc.dm"
#include "mode_stranded_attackers_process.dm"
#include "mode_stranded_attackers_spawn.dm"
#include "mode_stranded_evac.dm"
#include "mode_stranded_start.dm"
#include "mode_stranded_finish.dm"
#include "mode_stranded_resupply.dm"
