// Definitions for genes (trait groupings)
#define GENE_PRODUCTS "products"
#define GENE_CONSUMPTION "consumption"
#define GENE_ENVIRONMENT "environment"
#define GENE_RESISTANCE "resistance"
#define GENE_VIGOUR "vigour"
#define GENE_PIGMENT "appearance"
#define ALL_GENES list(GENE_PRODUCTS,GENE_CONSUMPTION,GENE_ENVIRONMENT,GENE_RESISTANCE,GENE_VIGOUR,GENE_PIGMENT)

//Definitions for traits (individual descriptors)
#define TRAIT_PRODUCTS             1
#define TRAIT_CHEMS                2
#define TRAIT_EXUDE_GASSES         3
#define TRAIT_ALTER_TEMP           4
#define TRAIT_POTENCY              5
#define TRAIT_HARVEST_REPEAT       6
#define TRAIT_PRODUCES_POWER       7
#define TRAIT_JUICY                8
#define TRAIT_PRODUCT_ICON         9
#define TRAIT_PLANT_ICON           10
#define TRAIT_CONSUME_GASSES       11
#define TRAIT_REQUIRES_NUTRIENTS   12
#define TRAIT_NUTRIENT_CONSUMPTION 13
#define TRAIT_REQUIRES_WATER       14
#define TRAIT_WATER_CONSUMPTION    15
#define TRAIT_CARNIVOROUS          16
#define TRAIT_PARASITE             17
#define TRAIT_STINGS               18
#define TRAIT_IDEAL_HEAT           19
#define TRAIT_HEAT_TOLERANCE       20
#define TRAIT_IDEAL_LIGHT          21
#define TRAIT_LIGHT_TOLERANCE      22
#define TRAIT_LOWKPA_TOLERANCE     23
#define TRAIT_HIGHKPA_TOLERANCE    24
#define TRAIT_EXPLOSIVE            25
#define TRAIT_TOXINS_TOLERANCE     26
#define TRAIT_PEST_TOLERANCE       27
#define TRAIT_WEED_TOLERANCE       28
#define TRAIT_ENDURANCE            29
#define TRAIT_YIELD                30
#define TRAIT_SPREAD               31
#define TRAIT_MATURATION           32
#define TRAIT_PRODUCTION           33
#define TRAIT_TELEPORTING          34
#define TRAIT_PLANT_COLOUR         35
#define TRAIT_PRODUCT_COLOUR       36
#define TRAIT_BIOLUM               37
#define TRAIT_BIOLUM_COLOUR        38
#define TRAIT_IMMUTABLE            39