#define OUTFIT_NONE                          EMPTY_BITFIELD
#define OUTFIT_HAS_JETPACK                   FLAG(0)
#define OUTFIT_HAS_BACKPACK                  FLAG(1)
#define OUTFIT_EXTENDED_SURVIVAL             FLAG(2)
#define OUTFIT_RESET_EQUIPMENT               FLAG(3)
#define OUTFIT_USES_ACCOUNT                  FLAG(4)
#define OUTFIT_USES_EMAIL                    FLAG(5)

#define OUTFIT_FLAGS_JOB_DEFAULT (OUTFIT_HAS_BACKPACK | OUTFIT_USES_ACCOUNT | OUTFIT_USES_EMAIL)

#define OUTFIT_ADJUSTMENT_SKIP_POST_EQUIP    FLAG(0)
#define OUTFIT_ADJUSTMENT_SKIP_SURVIVAL_GEAR FLAG(1)
#define OUTFIT_ADJUSTMENT_SKIP_ID_PDA        FLAG(2)
#define OUTFIT_ADJUSTMENT_PLAIN_HEADSET      FLAG(3)
#define OUTFIT_ADJUSTMENT_SKIP_BACKPACK      FLAG(4)

#define OUTFIT_ADJUSTMENT_ALL_SKIPS (OUTFIT_ADJUSTMENT_SKIP_POST_EQUIP|OUTFIT_ADJUSTMENT_SKIP_SURVIVAL_GEAR|OUTFIT_ADJUSTMENT_SKIP_ID_PDA|OUTFIT_ADJUSTMENT_SKIP_BACKPACK)
