#define AUTOSURGEON_START 0
#define AUTOSURGEON_INTERNAL 1
#define AUTOSURGEON_EXTERNAL 2
#define AUTOSURGEON_FIRST_AID 3
#define AUTOSURGEON_SPLINT 4
#define AUTOSURGEON_AUTOPSY 5
#define AUTOSURGEON_FINISH 6