/obj/item/modular_computer/on_death()
	break_apart()

/obj/item/modular_computer/proc/break_apart()
	visible_message("\The [src] breaks apart!")
	var/turf/newloc = get_turf(src)
	new /obj/item/stack/material/steel(newloc, round(steel_sheet_cost/2))
	for(var/obj/item/stock_parts/computer/H in get_all_components())
		uninstall_component(null, H)
		H.forceMove(newloc)
		if(prob(25))
			H.damage_health(rand(10,30))
	qdel(src)

/obj/item/modular_computer/damage_health(damage, damage_type, damage_flags, severity, skip_can_damage_check)
	// Damage components first, so that they're still caught if the computer dies and ejects them all.
	for (var/obj/item/stock_parts/computer/H in get_all_components())
		if (prob(50))
			var/component_damage = damage * (rand(75, 125) / 100)
			H.damage_health(component_damage, damage_type, damage_flags, severity, skip_can_damage_check)
	. = ..()
