name: Make and compile changelogs

on:
  push:
    branches:
    - dev

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  MakeCL:
    permissions:
      contents: write # required to push the changelog chunk yml commit
      pull-requests: read
    runs-on: ubuntu-22.04
    if: github.repository == 'Baystation12/Baystation12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get PR number
        id: pr
        run: |
          PR_NUM=$(gh pr list --search ${{ github.sha }} --state merged --json number -q '.[] | .number' || echo "")
          echo "PR number: $PR_NUM"
          echo "pull_request_number=$PR_NUM" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.x'
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub pyyaml bs4
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
      - name: Make CL
        env:
          BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR: "${{ steps.pr.outputs.pull_request_number }}"
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
        run: python tools/changelog/generate_cl.py
      - name: List CL files
        id: cl_files
        run: |
          CL_FILES=$(ls html/changelogs | grep -vwE 'example.yml|__CHANGELOG_README.txt' | wc -l || '0')
          echo "Number of changelog files: $CL_FILES"
          echo "cl_files=$CL_FILES" >> $GITHUB_OUTPUT
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
      - name: Compile CL
        run: python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
        if: ${{ steps.cl_files.outputs.cl_files != '0' }}
      - name: Commit And Push
        env:
          PR_NUMBER: ${{ steps.pr.outputs.pull_request_number }}
        run: |
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git config --global --unset credential.helper || true # this might not be needed, but it's just in case
          git config --unset-all http.https://github.com/.extraheader || true
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git commit -m "Automatic changelog generation for PR #$PR_NUMBER [ci skip]" -a
          git remote add changelog https://${{secrets.BOT_NAME}}:${{secrets.BOT_TOKEN}}@github.com/${{github.repository}}
          git push changelog dev
        if: ${{ steps.cl_files.outputs.cl_files != '0' }}
