name: Run Tests

env:
  CACHE_PREFIX: "test-1.1.2" # Update when this file is changed
  BYOND_SOURCE: "https://indm.dev/byond" # Canonical: "https://www.byond.com/download/build"
  BYOND_MAJOR: "516"
  BYOND_MINOR: "1679"
  SDMM_TARGET: "suite-1.11" # Refer to https://github.com/SpaceManiac/SpacemanDMM/releases

permissions:
  contents: read

on:
  push:
    branches-ignore: [ "gh-pages" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  preflight:
    name: Check Test Requirements
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      byond: ${{ steps.filter.outputs.byond }}

  dreamchecker:
    name: Dreamchecker
    runs-on: ubuntu-22.04
    needs:
    - preflight
    if: needs.preflight.outputs.byond == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Check dreamchecker cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: check-cache
        with:
          path: ~/spaceman_dmm/${{ env.SDMM_TARGET }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-spacemandmm-${{ env.SDMM_TARGET }}
      - name: Apply dreamchecker cache
        if: ${{ steps.check-cache.outputs.cache-hit }}
        run: |
          cp ~/spaceman_dmm/${{ env.SDMM_TARGET }}/dreamchecker ~
          chmod +x ~/dreamchecker
      - name: Fetch dreamchecker
        if: ${{ !steps.check-cache.outputs.cache-hit }}
        run: |
          wget -O ~/dreamchecker "https://github.com/SpaceManiac/SpacemanDMM/releases/download/${{ env.SDMM_TARGET }}/dreamchecker"
          mkdir -p ~/spaceman_dmm/${{ env.SDMM_TARGET }}/
          cp ~/dreamchecker ~/spaceman_dmm/${{ env.SDMM_TARGET }}/
          chmod +x ~/dreamchecker
      - name: Cache dreamchecker
        if: ${{ !steps.check-cache.outputs.cache-hit && success() }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/spaceman_dmm/${{ env.SDMM_TARGET }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-spacemandmm-${{ env.SDMM_TARGET }}
      - name: Run Dreamchecker
        run: ~/dreamchecker

  install_byond:
    name: Install BYOND
    runs-on: ubuntu-22.04
    needs:
    - preflight
    if: needs.preflight.outputs.byond == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Check Cached BYOND
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: check-cache
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Byond
        if: ${{ !steps.check-cache.outputs.cache-hit }}
        run: |
          sudo apt-get update
          sudo apt-get -y install file unzip
          chmod +x test/install-byond.sh
          test/install-byond.sh
      - name: Save BYOND Cache
        if: ${{ !steps.check-cache.outputs.cache-hit && success() }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}

  code_health:
    name: Code Health & Style
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.byond == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y uchardet
      - name: Run Tests
        env:
          TEST: CODE
        run: test/run-test.sh

  map_example:
    name: Unit Tests - Example Map
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.byond == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libcurl4:i386
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: example
        run: test/run-test.sh

  map_torch:
    name: Unit Tests - Torch Map
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.byond == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libcurl4:i386
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: torch
        run: test/run-test.sh

  map_dynamic:
    name: Unit Tests - Sites & Ruins
    runs-on: ubuntu-22.04
    needs:
    - preflight
    - dreamchecker
    - install_byond
    if: needs.preflight.outputs.byond == 'true'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/BYOND-${{ env.BYOND_MAJOR }}.${{ env.BYOND_MINOR }}
          key: ${{ env.CACHE_PREFIX }}-${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libcurl4:i386
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: away_sites_testing
        run: test/run-test.sh
